
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label lblProduc1;
	private global::Gtk.Entry txtn1;
	private global::Gtk.Entry txtn2;
	private global::Gtk.Entry txtn3;
	private global::Gtk.Label lblProduc3;
	private global::Gtk.Label lblProduc2;
	private global::Gtk.Entry txtSubtotal;
	private global::Gtk.Label lblSub;
	private global::Gtk.Entry txtIVA;
	private global::Gtk.Label lblIVA;
	private global::Gtk.Entry txtTotal;
	private global::Gtk.Label lblTotal;
	private global::Gtk.Button btnFact;
	private global::Gtk.Button btnClear;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProduc1 = new global::Gtk.Label ();
		this.lblProduc1.Name = "lblProduc1";
		this.lblProduc1.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 1");
		this.fixed1.Add (this.lblProduc1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProduc1]));
		w1.X = 98;
		w1.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtn1 = new global::Gtk.Entry ();
		this.txtn1.CanFocus = true;
		this.txtn1.Name = "txtn1";
		this.txtn1.IsEditable = true;
		this.txtn1.InvisibleChar = '●';
		this.fixed1.Add (this.txtn1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtn1]));
		w2.X = 185;
		w2.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtn2 = new global::Gtk.Entry ();
		this.txtn2.CanFocus = true;
		this.txtn2.Name = "txtn2";
		this.txtn2.IsEditable = true;
		this.txtn2.InvisibleChar = '●';
		this.fixed1.Add (this.txtn2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtn2]));
		w3.X = 185;
		w3.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtn3 = new global::Gtk.Entry ();
		this.txtn3.CanFocus = true;
		this.txtn3.Name = "txtn3";
		this.txtn3.IsEditable = true;
		this.txtn3.InvisibleChar = '●';
		this.fixed1.Add (this.txtn3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtn3]));
		w4.X = 186;
		w4.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProduc3 = new global::Gtk.Label ();
		this.lblProduc3.Name = "lblProduc3";
		this.lblProduc3.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 3");
		this.fixed1.Add (this.lblProduc3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProduc3]));
		w5.X = 98;
		w5.Y = 84;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProduc2 = new global::Gtk.Label ();
		this.lblProduc2.Name = "lblProduc2";
		this.lblProduc2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.lblProduc2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProduc2]));
		w6.X = 99;
		w6.Y = 48;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtSubtotal = new global::Gtk.Entry ();
		this.txtSubtotal.CanFocus = true;
		this.txtSubtotal.Name = "txtSubtotal";
		this.txtSubtotal.IsEditable = true;
		this.txtSubtotal.InvisibleChar = '●';
		this.fixed1.Add (this.txtSubtotal);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtSubtotal]));
		w7.X = 186;
		w7.Y = 136;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblSub = new global::Gtk.Label ();
		this.lblSub.Name = "lblSub";
		this.lblSub.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal");
		this.fixed1.Add (this.lblSub);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblSub]));
		w8.X = 106;
		w8.Y = 142;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtIVA = new global::Gtk.Entry ();
		this.txtIVA.CanFocus = true;
		this.txtIVA.Name = "txtIVA";
		this.txtIVA.IsEditable = true;
		this.txtIVA.InvisibleChar = '●';
		this.fixed1.Add (this.txtIVA);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtIVA]));
		w9.X = 187;
		w9.Y = 174;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblIVA = new global::Gtk.Label ();
		this.lblIVA.Name = "lblIVA";
		this.lblIVA.LabelProp = global::Mono.Unix.Catalog.GetString ("IVA");
		this.fixed1.Add (this.lblIVA);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblIVA]));
		w10.X = 133;
		w10.Y = 179;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtTotal = new global::Gtk.Entry ();
		this.txtTotal.CanFocus = true;
		this.txtTotal.Name = "txtTotal";
		this.txtTotal.IsEditable = true;
		this.txtTotal.InvisibleChar = '●';
		this.fixed1.Add (this.txtTotal);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtTotal]));
		w11.X = 188;
		w11.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblTotal = new global::Gtk.Label ();
		this.lblTotal.Name = "lblTotal";
		this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.lblTotal);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblTotal]));
		w12.X = 128;
		w12.Y = 216;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnFact = new global::Gtk.Button ();
		this.btnFact.CanFocus = true;
		this.btnFact.Name = "btnFact";
		this.btnFact.UseUnderline = true;
		this.btnFact.Label = global::Mono.Unix.Catalog.GetString ("Factura");
		this.fixed1.Add (this.btnFact);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnFact]));
		w13.X = 99;
		w13.Y = 281;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnClear = new global::Gtk.Button ();
		this.btnClear.CanFocus = true;
		this.btnClear.Name = "btnClear";
		this.btnClear.UseUnderline = true;
		this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.btnClear);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnClear]));
		w14.X = 230;
		w14.Y = 283;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 409;
		this.DefaultHeight = 414;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnFact.Clicked += new global::System.EventHandler (this.OnBtnFactClicked);
		this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
	}
}
